### ISSUE TITLE
CAFM-Connect-ProductsSample.ifcXML - Wrong and missing declaration

### ISSUE THREAD

**Issue by linhard** [buildingSMART/ProductData#36]
https://github.com/buildingSMART/ProductData/blob/master/SampleFiles/CAFM-Connect-ProductsSample/CAFM-Connect-ProductsSample.ifcXML

There is a template "i1273" with ApplicableEntity = "IfcDamper/FIREDAMPER" that relates to PropertySet "i3267". The "IfcRelDefinesByProperties" has RelatedObjects xsi:type="IfcBuildingElementProxy (i3259)" but should be "IfcDamper". The same within "IfcRelContainedInSpatialStructure".

 Also the "IfcDamper" (i3259) should have ObjectType = FIREDAMPER

**Comment by klacol** [comment]
Thank you. That were bugs. I corrected them. Please check and close, if the issue is resolved for you. 
(If the little point next to the GIT hash is green, the changes are valid against the IFC schema (XSD) and the IFC where-rules. This makes it more easy to see errors by regression.)

**Comment by klacol** [comment]
> (If the little point next to the GIT hash is green, the changes are valid against the IFC schema (XSD) and the IFC where-rules. This makes it more easy to see errors by regression.)

This is only partially true. On every commit, ALL files within this repo are validated. And since we have som file in here, that have never been valid, the icon is red on every commit, (until all files are made valid). Until then we have to klick on the icon and [read the related part in the validation log](https://ci.appveyor.com/project/klacol/productdata/builds/20925859#L189), to see, if the file is valid.
